name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGESTRY_TOKEN}}
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/artemyany/python:latest
          docker push ghcr.io/artemyany/python:latest
