name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGESTRY_TOKEN}}
      - name: 'Build Inventory Image'
        run: docker build . --tag ghcr.io/artemyany/python:latest
      - name: 'Test Image'
        run: |
          docker run -p 5000:5000 -d --rm ghcr.io/artemyany/python
          sleep 3
          curl 127.0.0.1:5000
      - name: 'Push Image'
        run: docker push ghcr.io/artemyany/python:latest